name: Bun Workflow

on:
  - push:
  - pull_request:

jobs:
  bun-simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: groupe-carvi/setup-environment@v1
        with:
          bun: true

      - name: Use Bun
        run: bun install
