name: Flutter Workflow

on:
  - push:
  - pull_request:

jobs:
  flutter-channel:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Android
          - platform: ubuntu-latest
            flutter-channel: stable

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: groupe-carvi/setup-environment@v1
        with:
          mobile: true

      - name: Use flutter
        run: flutter get
